package define

const SCORE_PLAYER_SHOOT_ENEMY_PLANE = 10
const SCORE_PLAYER_SHOOT_BULLET_CHEST = 50
const SCORE_PLAYER_SHOOT_FIXING_PACKET = 50
const SCORE_PLAYER_SHOOT_BOSS_PLANE = 100

const BULLET_CHEST_BULLET_COUNT = 80
const FIXING_PACKET_CURE = 40

const BULLET_OVERFLOW_BONUS = 2
const CURE_OVERFLOW_BONUS = 4
