package define

// 碰撞箱

const PLAYER_WIDTH = 80
const PLAYER_HEIGHT = 100

const ENEMY_PLANE_WIDTH = 90
const ENEMY_PLANE_HEIGHT = 90

const PLAYER_BULLET_WIDTH = 15
const ENEMY_BULLET_WIDTH = 15

const PLAYER_BULLET_HEIGHT = 15
const ENEMY_BULLET_HEIGHT = 15

const PLAYER_LASER_WIDTH = 15
const ENEMY_LASER_WIDTH = 15

const PLAYER_LASER_HEIGHT = 180
const ENEMY_LASER_HEIGHT = 180

const BULLET_CHEST_WIDTH = 60
const BULLET_CHEST_HEIGHT = 60

const FIXING_PACKET_WIDTH = 60
const FIXING_PACKET_HEIGHT = 60

const TNT_WIDTH = 32
const TNT_HEIGHT = 32
